import { Property } from "./validations";

export const properties: Property[] = [
  {
    id: "1",
    title: "Prodej bytu 2+kk 44 m², Jana Želivského, Praha",
    subtitle: "Nově nabízíme k prodeji krásný a praktický byt v osobním vlastnictví 2+kk o celkovém rozměru 44 m², který se nachází v 1. patře v jedné z nejžádanějších lokalit Prahy – Jana Želivského.",
    price: "Informace o ceně na vyžádání",
    link: "https://www.sreality.cz/detail/prodej/byt/2%2Bkk/praha-zizkov-jana-zelivskeho/1887937356",
    propertyType: "apartment",
    size: "44 m²",
    bedrooms: "2+kk",
    location: "Jana Želivského, Praha - Žižkov",
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Prodej bytu 1+kk 34 m², Jana Želivského, Praha",
    subtitle: "Prodej bytu 1+kk, 30 m², ve 2. patře domu s výtahem, v Praze 3 – Žižkov.",
    price: "Informace o ceně na vyžádání",
    link: "https://www.sreality.cz/detail/prodej/byt/1%2Bkk/praha-zizkov-jana-zelivskeho/2974266188",
    propertyType: "apartment",
    size: "34 m²",
    bedrooms: "1+kk",
    location: "Jana Želivského, Praha - Žižkov",
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Prodej bytu 1+kk 30 m², Jana Želivského, Praha",
    subtitle: "Tato část města prochází velkou proměnou a stává se jednou z nejžádanějších a nejvíc trendy čtvrtí v Praze, podobně jako sousední Karlín. Ceny nových bytů na Žižkově nyní rostou nejvíce v celé metropoli.",
    price: "Informace o ceně na vyžádání",
    link: "https://www.sreality.cz/detail/prodej/byt/1%2Bkk/praha-zizkov-jana-zelivskeho/396137292",
    propertyType: "apartment",
    size: "30 m²",
    bedrooms: "1+kk",
    location: "Jana Želivského, Praha - Žižkov",
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Prodej bytu 2+1 49 m², Seifertova, Praha - Žižkov",
    subtitle: "Byt 2+1 49 m² k prodeji Seifertova, Praha - Žižkov; sklep, výtah, patrový, osobní vlastnictví, ve velmi dobrém stavu.",
    price: "7 350 000 Kč",
    link: "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-zizkov-seifertova/979215180",
    propertyType: "apartment",
    size: "49 m²",
    bedrooms: "2+1",
    location: "Seifertova, Praha - Žižkov",
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Prodej rodinného domu 168 m², pozemek 281 m², Na Jarově, Praha - Žižkov",
    subtitle: "GLJ Partners nabízí k prodeji rodinný dům v klidné rezidenční části Prahy 3 Žižkov, v ulici Na Jarově. Nemovitost je ideální volbou pro dvougenerační bydlení nebo investici. V současné době je v řízení stavební projekt na rozšíření obytné plochy domu.",
    price: "Informace o ceně na vyžádání",
    link: "https://www.sreality.cz/detail/prodej/dum/rodinny/praha-zizkov-na-jarove/1448256332",
    propertyType: "house",
    size: "168 m²",
    bedrooms: "Multi-room",
    location: "Na Jarově, Praha - Žižkov",
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];